using IDFCR.Abstractions.Cli.ManagedStreams;

namespace IDFCR.TestUtilities;

/// <summary>
/// Represents a writeable stream that wraps a StringWriter, allowing it to be used as an IIOWriteableStream in testing scenarios. This class inherits from WriteableStreamBase, which provides the necessary implementation to write to the underlying StringWriter and expose it through the IIOWriteableStream interface. It is designed to facilitate testing of components that depend on writing output to a stream, enabling developers to easily capture string output for testing purposes without needing to interact with actual file streams or other I/O destinations. By using this class, developers can verify the output generated by their components in a controlled testing environment, making it easier to assert expected results and ensure correct behavior.
/// </summary>
/// <param name="writer">The StringWriter to wrap.</param>
public class StringWriteableStream(StringWriter writer) : WriteableStreamBase(writer)
{

}
