// <auto-generated />
using System;
using BuildTools.Infrastructure.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildTools.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(PackageManagerDbContext))]
    [Migration("20260412190748_AddedVersionLock_RowVersion")]
    partial class AddedVersionLock_RowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildTools.Infrastructure.SqlServer.Features.Packages.PackageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PackageId");

                    b.Property<string>("Alias")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_PackageId");

                    b.HasAlternateKey("Name", "Namespace")
                        .HasName("UQ_Package");

                    b.HasIndex("Namespace")
                        .HasDatabaseName("IDX_Package_Namespace");

                    b.ToTable("Package", "dbo");
                });

            modelBuilder.Entity("BuildTools.Infrastructure.SqlServer.Features.Packages.Version.PackageVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PackageVersionId")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_PackageVersionId");

                    b.Property<string>("CommitId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("LastErrorOnPublishAttemptTimestampUtc")
                        .HasColumnType("DATETIMEOFFSET(7)")
                        .HasColumnName("LastErrorOnPublishAttempt");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PublishedTimestampUtc")
                        .HasColumnType("DATETIMEOFFSET(7)");

                    b.Property<bool>("PublishedToFeed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ReleaseDateTimestampUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIMEOFFSET(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<string>("VersionPrefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VersionSuffix");

                    b.HasKey("Id")
                        .HasName("PK_PackageVersionId");

                    b.HasIndex("PackageId", "CommitId")
                        .HasDatabaseName("IX_PackageVersion_PackageId_CommitId");

                    b.HasIndex("PackageId", "VersionPrefix", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_PackageVersion");

                    b.ToTable("PackageVersion", (string)null);
                });

            modelBuilder.Entity("BuildTools.Infrastructure.SqlServer.Features.Packages.Version.VersionLockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VersionLockId")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_VersionLockId");

                    b.Property<DateTimeOffset>("LastRequestedTimestampUtc")
                        .HasColumnType("DATETIMEOFFSET(7)");

                    b.Property<DateTimeOffset?>("LockReleasedTimestampUtc")
                        .HasColumnType("DATETIMEOFFSET(7)");

                    b.Property<DateTimeOffset?>("LockedFromTimestampUtc")
                        .HasColumnType("DATETIMEOFFSET(7)");

                    b.Property<DateTimeOffset?>("LockedUntilTimestampUtc")
                        .HasColumnType("DATETIMEOFFSET(7)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RevisionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("VersionPrefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_VersionLockId");

                    b.HasIndex("PackageId", "VersionPrefix")
                        .IsUnique()
                        .HasDatabaseName("UQ_VersionLock_PackageId_VersionPrefix");

                    b.ToTable("VersionLock", (string)null);
                });

            modelBuilder.Entity("BuildTools.Infrastructure.SqlServer.Features.Settings.SettingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SettingId")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_SettingId");

                    b.Property<DateTimeOffset>("CreatedTimestampUtc")
                        .HasColumnType("DATETIMEOFFSET(7)")
                        .HasColumnName("CreatedTimestampUtc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("ModifiedTimestampUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIMEOFFSET(7)")
                        .HasColumnName("LastUpdatedTimestampUtc")
                        .HasDefaultValueSql("GETUTCDATE()", "DF_SystemConfig_Setting_LastUpdatedTimestampUtc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_SettingId");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UQ_SystemConfig_Setting_Key");

                    b.ToTable("Setting", "SYSTEM_CONFIG");
                });

            modelBuilder.Entity("BuildTools.Infrastructure.SqlServer.Features.Tags.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TagId")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_Tag_TagId");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Tag");

                    b.HasAlternateKey("Name")
                        .HasName("UQ_Tag_Name");

                    b.ToTable("Tag", "dbo");
                });

            modelBuilder.Entity("BuildTools.Infrastructure.SqlServer.Features.Packages.Version.PackageVersionEntity", b =>
                {
                    b.HasOne("BuildTools.Infrastructure.SqlServer.Features.Packages.PackageEntity", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PackageVersion_Package");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("BuildTools.Infrastructure.SqlServer.Features.Packages.Version.VersionLockEntity", b =>
                {
                    b.HasOne("BuildTools.Infrastructure.SqlServer.Features.Packages.PackageEntity", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_VersionLock_Package");
                });
#pragma warning restore 612, 618
        }
    }
}
